version: '3.7'

services:

  cengage:
    container_name: cengage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
