name: Deploy test-project on aws runner
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy cengage-aessment
    runs-on: self-hosted
    steps:
      # - name: Checkout
      #   uses: actions/checkout@master
      # - name: Setup Node
      #   uses: actions/setup-node@master
      #   with:
      #     node-version: '12.x'
      # - name: Install dependency
      #   run: yarn
      # - name: Build Production
      #   run: yarn build
      - name: Deploy
        run: |
          mkdir -p ~/projects/assessment
          rsync -a --delete . ~/projects/assessment
      - name: Start
        run: |    
          cd ~/projects/assessment && sudo docker-compose up -d --build
