name: Pull Request CI/CD

on: pull_request

jobs:
  primary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install
    - name: test
      run: yarn test
